from datetime import datetime
from xml.dom import minidom
import traceback
import argparse
import logging

import pefile


extra_header = """
    -
    This document was generated by Apymonitor.
    {} UTC
    A python project which generates a valid APIMonitor XML document with a PE as input.
    More info: github.com/felipetarijon/apymonitor""".format(datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S'))

xml_header = """<?xml version="1.0"?>
	<!--
	API Monitor Filter
	(c) 2010-2013, Rohitab Batra <rohitab@rohitab.com>
	http://www.rohitab.com/apimonitor/{}
	-->\n""".format(extra_header)


def get_pe_imports(pe_file_path: str):
    pe = pefile.PE(pe_file_path)
    imports = {}
    for entry in pe.DIRECTORY_ENTRY_IMPORT:
        imports[entry.dll.decode()] = [imp.name.decode() for imp in entry.imports]
    return imports


def get_pe_api_filters(pe_file_path: str):
    pe_imports = get_pe_imports(pe_file_path)

    doc = minidom.Document()

    root = doc.createElement('ApiMonitor')
    doc.appendChild(root)

    capture_filter = doc.createElement('CaptureFilter')
    root.appendChild(capture_filter)

    for dll in pe_imports:
        module = doc.createElement('Module')
        module.setAttribute('Name', dll)

        capture_filter.appendChild(module)
        
        for api_func in pe_imports[dll]:
            api = doc.createElement('Api')
            api.setAttribute('Name', api_func)

            module.appendChild(api)

    return root.toprettyxml()


if __name__ == '__main__':
    log_format = '[%(levelname)s] %(message)s'
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(logging.Formatter(log_format))
    console_handler.setLevel(logging.INFO)
    logger.addHandler(console_handler)

    # argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input",
                        help="Input file path", type=str)
    parser.add_argument("-o", "--output",
                        help="Output path", type=str)
    parser.add_argument("-s", "--silent", help="Do not output into stdout", action="store_true")

    args = parser.parse_args()

    pe_filters = get_pe_api_filters(args.input)

    if args.output:
        with open(args.output, "w+") as output_file:
            output_file.write(xml_header + pe_filters)
            output_file.close()
    
    if not args.silent:
        print(pe_filters)
